export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT';
export const GET_CART_LIST = 'GET_CART_LIST';